include:
  - project: "deeproute-projects/public/cicd-common"
    ref: development
    file: "/project-auth/global.gitlab-ci.yml"
  - project: "deeproute-projects/public/cicd-common"
    ref: development
    file: "/project-auth/build.gitlab-ci.yml"


stages:
  - deploy
 

variables:
  OPS_CI_CONTAINER_IMAGE_NAME: ml-platform-${CI_PROJECT_NAME}
  EXTRA_DOCKER_BUILD_ARGUMENT: " \
      --build-arg BUILD_API_GATEWAY=http://dev-mlp-api-gateway.deeproute.cn \
      --build-arg BUILD_NODE_ENV=${env_name}"

.build_docker:
    script:
        - docker build -t "$IMAGE" -t $IMAGE_LATEST -f $DOCKERFILE_NAME ${EXTRA_DOCKER_BUILD_ARGUMENT} .

  

deploy:
  extends: .deploy
  image: "${DEPLOY_IMAGE_NAME}:${DEPLOY_IMAGE_VERSION}"
  variables:
      DOCKERFILE_NAME: "Dockerfile"
      CUSTOM_SUB_IMAGE_NAME: ${CI_PROJECT_NAME}
  tags:
    - build
  before_script:
      - env_name=$CI_COMMIT_BRANCH
  rules:
    - if: $CI_COMMIT_BRANCH == "development"
      when: manual
    - if: $CI_COMMIT_BRANCH == "master"
      when: manual
