include:
    - project: 'deeproute-projects/public/cicd-common'
      ref: development
      file: '/project-build-env/global.gitlab-ci.yml'
    - project: 'deeproute-projects/public/cicd-common'
      ref: development
      file: '/project-build-env/build.gitlab-ci.yml'

stages:
  - build
 

variables:
  OPS_CI_CONTAINER_IMAGE_NAME: ml-platform-${CI_PROJECT_NAME}
  GIT_DEPTH: '1'
  OS: '${CI_COMMIT_REF_NAME}'
  DEPARTMENT: 'mlp'
  EXTRA_DOCKER_BUILD_ARGUMENT: " \
      --build-arg BUILD_API_GATEWAY=http://dev-mlp-api-gateway.deeproute.cn \
      --build-arg BUILD_NODE_ENV=development"

build:
  extends: .build
  variables:
    BUILD_PATH: "${EXTRA_DOCKER_BUILD_ARGUMENT} ."